highlycomposite/urls.py
from django.contrib import admin
from django.urls import path, include

from highlycomposite import views as highly_composite_views
from guides import views as guide_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', highly_composite_views.Home.as_view(), name='home'),
    path('heartbeat/', highly_composite_views.heartbeat, name='heartbeat'),
    path('guides/', guide_views.GuideList.as_view(), name='guide-list'),
    path('guides/<slug:slug>/', guide_views.GuideDetail.as_view(), name='guide-detail'),
    path('guides/<slug:slug>/markdown', guide_views.GuideDetail.as_view(
        template_name='guides/guide_detail.md',
        content_type='text/plain'),
        name='guide-detail-md'),
    path('steps/', guide_views.StepList.as_view(), name='step-list'),
    path('steps/<slug:slug>/', guide_views.StepDetail.as_view(), name='step-detail'),
]

guides/models.py
from django.db import models
from django.urls import reverse
from ordered_model.models import OrderedModel


class Guide(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    notes = models.TextField(default='', blank=True)
    steps = models.ManyToManyField('Step', through='GuideStep', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('guide-detail', args=[self.slug])


class GuideStep(OrderedModel):
    guide = models.ForeignKey('Guide', on_delete=models.CASCADE)
    step = models.ForeignKey('Step', on_delete=models.CASCADE)
    optional = models.BooleanField(default=False)
    order_with_respect_to = 'guide'


class Step(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    requirements = models.ManyToManyField('self', through='Requirement', symmetrical=False, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('step-detail', args=[self.slug])


class Requirement(OrderedModel):
    required_by = models.ForeignKey('Step', related_name='+', on_delete=models.CASCADE)
    requires = models.ForeignKey('Step', related_name='+', on_delete=models.CASCADE)
    order_with_respect_to = 'required_by'


class Action(OrderedModel):
    text = models.TextField()
    step = models.ForeignKey(Step, related_name='actions', on_delete=models.CASCADE)
    order_with_respect_to = 'step'


class Verification(OrderedModel):
    text = models.TextField()
    step = models.ForeignKey('Step', related_name='verifications', on_delete=models.CASCADE)
    order_with_respect_to = 'step'

guides/views.py
from django.views.generic import DetailView, ListView

from guides.models import Guide, Step


class GuideDetail(DetailView):
    model = Guide


class GuideList(ListView):
    model = Guide


class StepDetail(DetailView):
    model = Step


class StepList(ListView):
    model = Step

highlycomposite/views.py
from django.views.generic import TemplateView
from django.http import HttpRequest, HttpResponse


def heartbeat(request: HttpRequest) -> HttpResponse:
    return HttpResponse(status=200)


class Home(TemplateView):
    template_name = 'home.html'

templates/guides/guide_detail.html
{% load guides %}
{% include 'header.html' %}
<main role="main" class="flex-shrink-0">
    <div class="container">
        <h1 class="mt-5">{{ guide.title }}</h1><br>
        {% for guide_step in guide.guidestep_set.all %}
            {% include 'guides/step_card.html'  with step=guide_step.step %}
        {% endfor %}
    </div>
</main>
{% include 'footer.html' %}

templates/guides/guide_list.html
{% include 'header.html' %}
<main role="main" class="flex-shrink-0">
    <div class="container">
    <h1 class="mt-5">Guides</h1>
        <ul>
            {% for guide in guide_list %}
                <li><a href="{{ guide.get_absolute_url }}">{{ guide.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
</main>
{% include 'footer.html' %}

templates/guides/step_card.html
{% load guides %}
<div class="card border-dark mb-3 w-75" id="card-{{ step.slug }}">
    <h2 class="card-header">
        {{ step.title }}{% if guide_step.optional %}<small class="text-muted"> (optional)</small>{% endif %}
    </h2>
    <div class="card-body">
        {% if step.requirements.exists %}
            <h4 class="card-title">Requirements</h4>
            <ul>
                {% for requirement in step.requirements.all %}
                    <li><a href="{% if requirement in guide.steps.all %}#card-{{ requirement.slug }}{% else %}{{ requirement.get_absolute_url }}{% endif %}">{{ requirement.title }}</a></li>
                {% endfor %}
            </ul>
            <hr />
        {% endif %}
        <h4 class="card-title">Actions</h4>
        <ol>
            {% for action in step.actions.all %}
                <li>{{ action.text|markdown|safe }}</li>
            {% endfor %}
        </ol>
        <hr />
        <h4 class="card-title">Verifications</h4>
        {% for verification in step.verifications.all %}
            <div>{{ verification.text|markdown|safe }}</div>
        {% endfor %}
    </div>
</div>

templates/guides/step_detail.html
{% load guides %}
{% include 'header.html' %}
<main role="main" class="flex-shrink-0">
    <div class="container">
        {% include 'guides/step_card.html' %}
    </div>
</main>
{% include 'footer.html' %}

templates/guides/step_list.html
{% include 'header.html' %}
<main role="main" class="flex-shrink-0">
    <div class="container">
    <h1 class="mt-5">Steps</h1>
        <ul>
            {% for step in step_list %}
                <li><a href="{{ step.get_absolute_url }}">{{ step.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
</main>
{% include 'footer.html' %}

templates/header.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
    <title>Highly Composite</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
<header>
    {% include 'nav_bar.html' %}
</header>

templates/home.html
{% load socialaccount %}

<h1>Home</h1>
{% if user.is_authenticated %}
<p>Welcome {{ user.username }}</p>
{% endif %}

templates/nav_bar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Highly Composite</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03"
            aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor03">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'guide-list' %}">Guides</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'step-list' %}">Steps</a>
            </li>
        </ul>
    </div>
</nav>